__1.	Write a Python Program to Add Two Matrices?__

In [3]:
import numpy as np
A = np.random.randint(10,30,size=(3,3))
B = np.random.randint(15,40,size=(3,3))

print("First Array : \n ",A,"\n")
print()
print("Second Array : \n ",B," \n")
print("Sum of the Two Metrix \n",A+B)

First Array : 
  [[21 21 13]
 [25 14 10]
 [11 24 19]] 


Second Array : 
  [[22 24 18]
 [33 18 39]
 [28 15 19]]  

Sum of the Two Metrix 
 [[43 45 31]
 [58 32 49]
 [39 39 38]]


__2.	Write a Python Program to Multiply Two Matrices?__

In [7]:
import numpy as np
Mul1 = np.random.randint(1,15,size=(3,3))
Mult2 = np.random.randint(15,25,size=(3,3))
print("First Matrice \n", Mul1,"\n")
print("Second Matrice \n", Mult2, "\n")
print("Multiplication of two Matrice is \n",Mul1*Mult2)

First Matrice 
 [[ 6  2  6]
 [ 1 10 12]
 [ 9  2  3]] 

Second Matrice 
 [[17 22 24]
 [21 21 22]
 [22 24 22]] 

Multiplication of two Matrice is 
 [[102  44 144]
 [ 21 210 264]
 [198  48  66]]


__3.	Write a Python Program to Transpose a Matrix?__

In [11]:
import numpy as np
matrix = np.random.randint(1,10,size= (3,3))
print("Origanla Matrix is \n ",matrix," \n \n")

print("Transpose Of matrix is \n",matrix.T)

Origanla Matrix is 
  [[5 6 2]
 [8 4 1]
 [9 1 9]]  
 

Transpose Of matrix is 
 [[5 8 9]
 [6 4 1]
 [2 1 9]]


__4.	Write a Python Program to Sort Words in Alphabetic Order?__

In [21]:
Word = input("Enter the String").lower().split(" ")
print(sorted(Word))


Enter the StringThomas Markas Patole
['markas', 'patole', 'thomas']


__5.	Write a Python Program to Remove Punctuation From a String?__

In [2]:
import string
Value = input("Enter the String")
for i in string.punctuation:
    Value = Value.replace(i," ")

print(Value)

Enter the String!hi. wh?at is the weat[h]er lik?e.
 hi  wh at is the weat h er lik e 
